### PR TITLE
Py3 support

### PR DESCRIPTION
**Pull request by kayibal**
This is based on #13. Basically just fixes the tests on travis. 

I've had to fix the hex encoding for python3.3. I've also added the new dependency `future` to setup.py so the package is pip installable. I removed python2.6 from travis.yml as the tests were not passing and support for it will be dropped soon anyway.

### CODE REVIEW

**Comment by kayibal** [comment]
@tuulos Could you have a look over this?

**Comment by tuulos** [comment]
@kayibal thanks! Have you tested this with Py 2.7?

**Comment by kayibal** [comment]
Yes, look [here](https://travis-ci.org/traildb/traildb-python/jobs/210352947) it's tested also for python 3.3, 3.4 and 3.5

**Comment by kayibal** [comment]
@tuulos Any update on this?

**Pull request merged**
